### ISSUE TITLE
[Bug] Selected Teammates Being Copied Between Characters

### ISSUE THREAD

**Issue by WolfBungalow** [fribbels/hsr-optimizer#683]
# Issue Template

## Description
On the character optimizer tab, a teammate or light cone selected under a character populates on the next selected character to optimize. It only populates if the character slot or light cone is empty. 

## Steps to Reproduce

1. Open the optimizer to a character, clear their teammates.
2. Open the optimizer to another character, either select a teammate or have one already present.
3. Go back to the first character.

## Expected Behavior
Selected teammates and teammate light cones should persist between optimize selected characters.

## Screenshots
https://youtu.be/YkJBCDcBxgQ

## Additional Information
GOOD:	4243098
BAD:	81fb727

Tried changing undefined to null and that seemed to stop the teammate cloning but not the light cone, and I didn't know what else that would break.

```
export function defaultTeammate() {
  const teammate: Partial<Teammate> = {
    characterId: undefined,
    characterEidolon: 0,
    lightCone: undefined,
    lightConeSuperimposition: 1,
  }
  return teammate
} 
```

**Comment by WolfBungalow** [comment]
I found the fix prevents the cloning of the teammate, but it doesn't stop the cloning of the teammate's light cone.

The light cone will continue to clone if the user has never selected or deleted a light cone for the subsequent character's teammate [https://www.youtube.com/watch?v=YkJBCDcBxgQ&t=15s](https://www.youtube.com/watch?v=YkJBCDcBxgQ&t=15s)

**Comment by fribbels** [comment]
I believe this should already be fixed in beta https://fribbels.github.io/dreary-quibbles/

**Comment by WolfBungalow** [comment]
Still broken for light cones with my local git pull of beta and the https://fribbels.github.io/dreary-quibbles site. I'm using a fresh incognito with only two manually added characters.
